version: "3"
services:
  app:
    build: ./app
    ports:
      - "5000:5000"

    depends_on:
      - db
    networks:
    - backend-network
    - frontend-network
    restart: always
    volumes:
      - ./app:/app

  db:
    build: ./db
    ports:
      - "3306:3306"

    volumes:
      #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
    networks:
    - backend-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
    - backend-network
    - frontend-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - frontend-network

networks:
  backend-network:
  frontend-network:
volumes:
  data:
secrets:
  db-password:
    file: db/password.txt


